id: P000695
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6013
  title: བོད་བཙན་པོའི་དུས་ཀྱི་རྩོམ་རིག
  author: ''
  volumes:
    9298959e29b54841aec0b11a42261cac:
      image_group_id: I1KG6040
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
